/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sukiva;

import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import java.awt.Font;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Snake_Eye
 */
public class bill extends javax.swing.JInternalFrame {
 DefaultTableModel defaultTableModel = new DefaultTableModel();
    /**
     * Creates new form bill
     */
    public bill() {
        initComponents();
         BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        
          tdri.setBackground(new java.awt.Color(0,0,0,1));
          tdrn.setBackground(new java.awt.Color(0,0,0,1));

        tqua.setBackground(new java.awt.Color(0,0,0,1));
        tunp.setBackground(new java.awt.Color(0,0,0,1));
         tta.setBackground(new java.awt.Color(0,0,0,1));
          tdis.setBackground(new java.awt.Color(0,0,0,0));

         
          scroll.setBackground(new java.awt.Color(0,0,0,1));
        scroll.getViewport().setBackground(new java.awt.Color(0,0,0,1));
        st.setBackground(new java.awt.Color(0,0,0,1));
     
        JTableHeader header = st.getTableHeader();
                header.setEnabled(false);
        header.setBackground(new java.awt.Color(0,0,0,0));
        st.getTableHeader().setFont(new Font("Times New Roman", Font.BOLD, 14));
        
    
        Object columns[] = {"Drugs Name","Unitprice","Quantity","Total"};
        defaultTableModel.setColumnIdentifiers(columns);
        st.setModel(defaultTableModel);
        
        
        ((JTextFieldDateEditor)tdd.getDateEditor()).setBackground(new java.awt.Color(0,0,0,1));
        ((JTextFieldDateEditor)tdd.getDateEditor()).setBorder(javax.swing.BorderFactory.createEmptyBorder());
        (tdd.getCalendarButton()).setBackground(new java.awt.Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dri = new javax.swing.JLabel();
        tdrn = new javax.swing.JTextField();
        tdri = new javax.swing.JTextField();
        drn = new javax.swing.JLabel();
        qua = new javax.swing.JLabel();
        tqua = new javax.swing.JTextField();
        unp = new javax.swing.JLabel();
        tunp = new javax.swing.JTextField();
        ta = new javax.swing.JLabel();
        tta = new javax.swing.JTextField();
        gb = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        scroll = new javax.swing.JScrollPane();
        st = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        tdis = new javax.swing.JComboBox<>();
        tdd = new com.toedter.calendar.JDateChooser();
        dd = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(960, 560));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dri.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        dri.setForeground(new java.awt.Color(0, 0, 0));
        dri.setText("Drug ID");
        getContentPane().add(dri, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, 30));

        tdrn.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        tdrn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tdrn.setOpaque(false);
        tdrn.setPreferredSize(new java.awt.Dimension(6, 22));
        tdrn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdrnActionPerformed(evt);
            }
        });
        getContentPane().add(tdrn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 160, 20));

        tdri.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        tdri.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tdri.setOpaque(false);
        tdri.setPreferredSize(new java.awt.Dimension(6, 22));
        getContentPane().add(tdri, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 160, 20));

        drn.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        drn.setForeground(new java.awt.Color(0, 0, 0));
        drn.setText("Drug Name");
        getContentPane().add(drn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 30));

        qua.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        qua.setForeground(new java.awt.Color(0, 0, 0));
        qua.setText("Quantity");
        getContentPane().add(qua, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, 30));

        tqua.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        tqua.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tqua.setOpaque(false);
        tqua.setPreferredSize(new java.awt.Dimension(6, 22));
        getContentPane().add(tqua, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 160, 20));

        unp.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        unp.setForeground(new java.awt.Color(0, 0, 0));
        unp.setText("Unit price");
        getContentPane().add(unp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 120, 30));

        tunp.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        tunp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tunp.setOpaque(false);
        tunp.setPreferredSize(new java.awt.Dimension(6, 22));
        getContentPane().add(tunp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 160, 20));

        ta.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        ta.setForeground(new java.awt.Color(0, 0, 0));
        ta.setText("Total Amount");
        getContentPane().add(ta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 120, 30));

        tta.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        tta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tta.setOpaque(false);
        tta.setPreferredSize(new java.awt.Dimension(6, 22));
        getContentPane().add(tta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 160, 20));

        gb.setBackground(new java.awt.Color(176, 106, 179));
        gb.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        gb.setForeground(new java.awt.Color(0, 0, 204));
        gb.setText("Genarate Bill");
        getContentPane().add(gb, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 220, 50));

        jButton2.setBackground(new java.awt.Color(176, 106, 179));
        jButton2.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 204));
        jButton2.setText("Delete");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 80, 40));

        jButton3.setBackground(new java.awt.Color(176, 106, 179));
        jButton3.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 204));
        jButton3.setText("Update");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 90, 40));

        scroll.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        scroll.setOpaque(false);

        st.setBackground(new java.awt.Color(176, 106, 179));
        st.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        st.setFont(new java.awt.Font("Ebrima", 0, 10)); // NOI18N
        st.setForeground(new java.awt.Color(0, 0, 0));
        st.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        st.setGridColor(new java.awt.Color(0, 0, 0));
        st.setOpaque(false);
        scroll.setViewportView(st);

        getContentPane().add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 610, 530));

        jButton5.setBackground(new java.awt.Color(176, 106, 179));
        jButton5.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 204));
        jButton5.setText("Add");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 80, 40));

        tdis.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        tdis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Credit", "Cash" }));
        tdis.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tdis.setOpaque(false);
        tdis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdisActionPerformed(evt);
            }
        });
        getContentPane().add(tdis, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 220, 30));

        tdd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tdd.setOpaque(false);
        tdd.setPreferredSize(new java.awt.Dimension(22, 6));
        getContentPane().add(tdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 160, 30));

        dd.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        dd.setForeground(new java.awt.Color(0, 0, 0));
        dd.setText("Purchase Date");
        getContentPane().add(dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 130, 30));

        bg.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sukiva/images/internal.png"))); // NOI18N
        bg.setText("jLabel1");
        bg.setMaximumSize(new java.awt.Dimension(998, 580));
        bg.setMinimumSize(new java.awt.Dimension(998, 580));
        bg.setPreferredSize(new java.awt.Dimension(960, 560));
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tdrnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdrnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdrnActionPerformed

    private void tdisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel dd;
    private javax.swing.JLabel dri;
    private javax.swing.JLabel drn;
    private javax.swing.JButton gb;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel qua;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable st;
    private javax.swing.JLabel ta;
    private com.toedter.calendar.JDateChooser tdd;
    private javax.swing.JComboBox<String> tdis;
    private javax.swing.JTextField tdri;
    private javax.swing.JTextField tdrn;
    private javax.swing.JTextField tqua;
    private javax.swing.JTextField tta;
    private javax.swing.JTextField tunp;
    private javax.swing.JLabel unp;
    // End of variables declaration//GEN-END:variables
}
