/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sukiva;

import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import static sukiva.Admin.q;

/**
 *
 * @author Snake_Eye
 */
public class CashinHand extends javax.swing.JInternalFrame {
  DefaultTableModel defaultTableModel = new DefaultTableModel();
Connection connection = null;
    PreparedStatement prp = null;
    ResultSet rs = null;
    java.util.Date date;
   java.sql.Date sqlda;
   int del;
    /**
     * Creates new form accounts
     */
    public CashinHand() {
        initComponents();
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
         connection = DataBase.database.ConnectDb();
        
        tasearch.setBackground(new java.awt.Color(0,0,0,0));
        taser.setBackground(new java.awt.Color(0,0,0,0));
        tasearch2.setBackground(new java.awt.Color(0,0,0,1));
        tades.setBackground(new java.awt.Color(0,0,0,1));
         taamt.setBackground(new java.awt.Color(0,0,0,1));
         
         
         
         
           
          ascroll.setBackground(new java.awt.Color(0,0,0,1));
        ascroll.getViewport().setBackground(new java.awt.Color(0,0,0,1));
         at.setBackground(new java.awt.Color(0,0,0,1));
     
         
         JTableHeader header = at.getTableHeader();
                 header.setEnabled(false);
        header.setBackground(new java.awt.Color(0,0,0,0));
        at.getTableHeader().setFont(new Font("Times New Roman", Font.BOLD, 14));
        
    
        Object columns[] = {"ID","Date","Description"," Debit","Credit"};
        defaultTableModel.setColumnIdentifiers(columns);
        at.setModel(defaultTableModel);
         at.setDefaultEditor(Object.class, null);
        
        
        
        ((JTextFieldDateEditor)tadate1.getDateEditor()).setBackground(new java.awt.Color(0,0,0,1));
        ((JTextFieldDateEditor)tadate1.getDateEditor()).setBorder(javax.swing.BorderFactory.createEmptyBorder());
        (tadate1.getCalendarButton()).setBackground(new java.awt.Color(0,0,0,0));
        
        ((JTextFieldDateEditor)taser.getDateEditor()).setBackground(new java.awt.Color(0,0,0,1));
        ((JTextFieldDateEditor)taser.getDateEditor()).setBorder(javax.swing.BorderFactory.createEmptyBorder());
        (taser.getCalendarButton()).setBackground(new java.awt.Color(0,0,0,0));
        loadData();
        
    }
public void loadData() {
        //Object columns[] = {"ID","Description"," Debit","Credit"};
        String sql = "SELECT `describtion`, `amountcash`, `datecash`, `debitcash`, `creaditcash`, `cashid` FROM `cashinhand`";
        try {
            prp = connection.prepareStatement(sql);
            rs = prp.executeQuery();
            Object columnData[] = new Object[7];
            while (rs.next()) {
                columnData[0] = rs.getString("cashid");
                columnData[1] = rs.getString("datecash");
                columnData[2] = rs.getString("describtion");
                columnData[3] = rs.getString("debitcash");
                columnData[4] = rs.getString("creaditcash");
                  defaultTableModel.addRow(columnData);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        tades.setText(null);
        taamt.setText(null);
        tadate1.setDate(null);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ades = new javax.swing.JLabel();
        aamt = new javax.swing.JLabel();
        tades = new javax.swing.JTextField();
        taser = new com.toedter.calendar.JDateChooser();
        adate = new javax.swing.JLabel();
        credit = new javax.swing.JButton();
        adelete = new javax.swing.JButton();
        eupdate = new javax.swing.JButton();
        asearch = new javax.swing.JButton();
        tasearch = new javax.swing.JComboBox<>();
        tasearch2 = new javax.swing.JTextField();
        taamt = new javax.swing.JTextField();
        debit1 = new javax.swing.JButton();
        ascroll = new javax.swing.JScrollPane();
        at = new javax.swing.JTable();
        tadate1 = new com.toedter.calendar.JDateChooser();
        bdes1 = new javax.swing.JLabel();
        csts = new javax.swing.JLabel();
        bamt1 = new javax.swing.JLabel();
        ccre = new javax.swing.JLabel();
        cde = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(960, 560));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ades.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        ades.setForeground(new java.awt.Color(0, 0, 0));
        ades.setText("Description");
        getContentPane().add(ades, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, 30));

        aamt.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        aamt.setForeground(new java.awt.Color(0, 0, 0));
        aamt.setText("Amount");
        getContentPane().add(aamt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 120, 30));

        tades.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        tades.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tades.setOpaque(false);
        tades.setPreferredSize(new java.awt.Dimension(6, 22));
        getContentPane().add(tades, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 160, 20));

        taser.setBackground(new java.awt.Color(176, 106, 179));
        taser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        taser.setForeground(new java.awt.Color(176, 106, 179));
        taser.setOpaque(false);
        taser.setPreferredSize(new java.awt.Dimension(22, 6));
        getContentPane().add(taser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 160, 30));

        adate.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        adate.setForeground(new java.awt.Color(0, 0, 0));
        adate.setText("Date");
        getContentPane().add(adate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 120, 30));

        credit.setBackground(new java.awt.Color(176, 106, 179));
        credit.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        credit.setForeground(new java.awt.Color(0, 0, 204));
        credit.setText("CREDIT");
        credit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditActionPerformed(evt);
            }
        });
        getContentPane().add(credit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 90, 40));

        adelete.setBackground(new java.awt.Color(176, 106, 179));
        adelete.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        adelete.setForeground(new java.awt.Color(0, 0, 204));
        adelete.setText("Delete");
        adelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adeleteActionPerformed(evt);
            }
        });
        getContentPane().add(adelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 80, 40));

        eupdate.setBackground(new java.awt.Color(176, 106, 179));
        eupdate.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        eupdate.setForeground(new java.awt.Color(0, 0, 204));
        eupdate.setText("update");
        eupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eupdateActionPerformed(evt);
            }
        });
        getContentPane().add(eupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 90, 40));

        asearch.setBackground(new java.awt.Color(176, 106, 179));
        asearch.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        asearch.setForeground(new java.awt.Color(0, 0, 204));
        asearch.setText("Search");
        asearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asearchActionPerformed(evt);
            }
        });
        getContentPane().add(asearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 110, 30));

        tasearch.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        tasearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Date", "Description" }));
        tasearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tasearch.setOpaque(false);
        getContentPane().add(tasearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 110, 30));

        tasearch2.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        tasearch2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tasearch2.setOpaque(false);
        tasearch2.setPreferredSize(new java.awt.Dimension(6, 22));
        tasearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tasearch2ActionPerformed(evt);
            }
        });
        getContentPane().add(tasearch2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 160, 30));

        taamt.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        taamt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        taamt.setOpaque(false);
        taamt.setPreferredSize(new java.awt.Dimension(6, 22));
        getContentPane().add(taamt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 160, 20));

        debit1.setBackground(new java.awt.Color(176, 106, 179));
        debit1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        debit1.setForeground(new java.awt.Color(0, 0, 204));
        debit1.setText("DEBIT");
        debit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debit1ActionPerformed(evt);
            }
        });
        getContentPane().add(debit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 80, 40));

        ascroll.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ascroll.setOpaque(false);

        at.setBackground(new java.awt.Color(176, 106, 179));
        at.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        at.setFont(new java.awt.Font("Ebrima", 0, 10)); // NOI18N
        at.setForeground(new java.awt.Color(0, 0, 0));
        at.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        at.setGridColor(new java.awt.Color(0, 0, 0));
        at.setOpaque(false);
        at.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atMouseClicked(evt);
            }
        });
        ascroll.setViewportView(at);

        getContentPane().add(ascroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 610, 530));

        tadate1.setBackground(new java.awt.Color(176, 106, 179));
        tadate1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tadate1.setForeground(new java.awt.Color(176, 106, 179));
        tadate1.setOpaque(false);
        tadate1.setPreferredSize(new java.awt.Dimension(22, 6));
        getContentPane().add(tadate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 160, 30));

        bdes1.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        bdes1.setForeground(new java.awt.Color(0, 0, 0));
        bdes1.setText("Debit");
        getContentPane().add(bdes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 120, 30));

        csts.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        csts.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(csts, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 310, 30));

        bamt1.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        bamt1.setForeground(new java.awt.Color(0, 0, 0));
        bamt1.setText("Credit");
        getContentPane().add(bamt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 120, 30));

        ccre.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        ccre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(ccre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 160, 20));

        cde.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        cde.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(cde, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 160, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sukiva/images/internal.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void asearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asearchActionPerformed

    private void tasearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tasearch2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tasearch2ActionPerformed

    private void debit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debit1ActionPerformed
        // TODO add your handling code here:
        String dis=tades.getText();
        Double amount=Double.parseDouble(taamt.getText());
         
        date=tadate1.getDate();
        sqlda= new java.sql.Date(date.getTime());
       


         if(dis.equals("")||amount.equals("")||amount.equals("")||date.equals("")){

            JOptionPane.showMessageDialog(null,"Complete Your Account Information","Missing Information",2);

        }
        else {
            String sql = "INSERT INTO `cashinhand`(`describtion`, `amountcash`, `datecash`, `debitcash`)  VALUES (?,?,?,?)";
            if (connection != null) {

                try {
                    prp = connection.prepareStatement(sql);
                    prp.setString(1, dis);
                    prp.setDouble(2, amount);
                     prp.setDate(3, sqlda);
                    prp.setDouble(4, amount);
                
                    
                    prp.execute();
                    defaultTableModel.getDataVector().removeAllElements();
                    defaultTableModel.fireTableDataChanged();
                    loadData();
                    JOptionPane.showMessageDialog(null, "Data Saved");
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }
        
        
    }//GEN-LAST:event_debit1ActionPerformed

    private void creditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditActionPerformed
        // TODO add your handling code here:
        String dis=tades.getText();
        Double amount=Double.parseDouble(taamt.getText());
      
        date=tadate1.getDate();
        sqlda= new java.sql.Date(date.getTime());
       


         if((dis.equals(""))||(taamt.getText().equals(""))){

            JOptionPane.showMessageDialog(null,"Complete Your Account Information","Missing Information",2);

        }
        else {
            String sql = "INSERT INTO `cashinhand`(`describtion`, `amountcash`, `datecash`, `creaditcash` )  VALUES (?,?,?,?)";
            if (connection != null) {

                try {
                    prp = connection.prepareStatement(sql);
                    prp.setString(1, dis);
                    prp.setDouble(2, amount);
                     prp.setDate(3, sqlda);
                    prp.setDouble(4, amount);
                   
                  
                    
                    prp.execute();
                    defaultTableModel.getDataVector().removeAllElements();
                    defaultTableModel.fireTableDataChanged();
                    loadData();
                    JOptionPane.showMessageDialog(null, "Data Saved");
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }
    }//GEN-LAST:event_creditActionPerformed

    private void adeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adeleteActionPerformed
        // TODO add your handling code here:
        
        
         String sql = "DELETE FROM `cashinhand` WHERE cashid ='" + del + "'";
        try {
            prp = connection.prepareStatement(sql);
            prp.execute();
            JOptionPane.showMessageDialog(null, "Record has been deleted");
            defaultTableModel.getDataVector().removeAllElements();
            defaultTableModel.fireTableDataChanged();
            loadData();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Record not found");
        }
        
    }//GEN-LAST:event_adeleteActionPerformed

    private void atMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atMouseClicked
        // TODO add your handling code here:
            Object columns[] = {"ID","Date","Description"," Debit","Credit"};

         int row = at.getSelectedRow(); 
            try {
             java.util.Date h = new SimpleDateFormat("yyyy-MM-dd").parse((String)at.getValueAt(row, 1).toString());
              tadate1.setDate(h);
              
             } catch (ParseException ex) {
                     Logger.getLogger(CashinHand.class.getName()).log(Level.SEVERE, null, ex);
                }
             
        tades.setText(at.getValueAt(row, 2).toString());
    
          if("0.0".equals(at.getValueAt(row, 3).toString()))
          {
              taamt.setText(at.getValueAt(row, 4).toString());
          }
          else if("0.0".equals(at.getValueAt(row, 4).toString()))
          {
               taamt.setText(at.getValueAt(row, 3).toString());
          }
         
         
        
         del = Integer.parseInt(at.getValueAt(row, 0).toString());
        
    }//GEN-LAST:event_atMouseClicked

    private void eupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eupdateActionPerformed
        // TODO add your handling code here:
        int row = at.getSelectedRow(); 
            String cname=tades.getText();
        Double amount=Double.parseDouble(taamt.getText());
        
        date=tadate1.getDate();
        sqlda= new java.sql.Date(date.getTime());
        
       


         if(cname.equals("")||amount.equals("")){

            JOptionPane.showMessageDialog(null,"Complete Your Account Information","Missing Information",2);

        }
        else if("0.0".equals(at.getValueAt(row, 3).toString()))
         {
            String sql = "UPDATE `cashinhand` SET `describtion`='"+cname+"',`amountcash`='"+amount+"',`datecash`='"+sqlda+"',`creaditcash`='"+amount+"' WHERE `cashid`='"+del+"'";
            if (connection != null) {

                try {    
                     prp = connection.prepareStatement(sql);
                    prp.execute();
                    defaultTableModel.getDataVector().removeAllElements();
                    defaultTableModel.fireTableDataChanged();
                    loadData();
                      q.removeAll();
                      CashinHand ne = new CashinHand();
                        q.add(ne).setVisible(true);
                    JOptionPane.showMessageDialog(null, "Data Saved");
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }
         else if("0.0".equals(at.getValueAt(row, 4).toString()))
         {
            String sql = "UPDATE `cashinhand` SET `describtion`='"+cname+"',`amountcash`='"+amount+"',`datecash`='"+sqlda+"',`debitcash`='"+amount+"' WHERE `cashid`='"+del+"'";
            if (connection != null) {

                try {    
                     prp = connection.prepareStatement(sql);
                    prp.execute();
                    defaultTableModel.getDataVector().removeAllElements();
                    defaultTableModel.fireTableDataChanged();
                    loadData();
                      q.removeAll();
                          CashinHand ne = new CashinHand();
                             q.add(ne).setVisible(true);
                    JOptionPane.showMessageDialog(null, "Data Saved");
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }
        
        
        
    }//GEN-LAST:event_eupdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aamt;
    private javax.swing.JLabel adate;
    private javax.swing.JButton adelete;
    private javax.swing.JLabel ades;
    private javax.swing.JScrollPane ascroll;
    private javax.swing.JButton asearch;
    private javax.swing.JTable at;
    private javax.swing.JLabel bamt1;
    private javax.swing.JLabel bdes1;
    private javax.swing.JLabel ccre;
    private javax.swing.JLabel cde;
    private javax.swing.JButton credit;
    private javax.swing.JLabel csts;
    private javax.swing.JButton debit1;
    private javax.swing.JButton eupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField taamt;
    private com.toedter.calendar.JDateChooser tadate1;
    private javax.swing.JTextField tades;
    private javax.swing.JComboBox<String> tasearch;
    private javax.swing.JTextField tasearch2;
    private com.toedter.calendar.JDateChooser taser;
    // End of variables declaration//GEN-END:variables
}
