/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sukiva;

import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import static sukiva.Admin.q;

/**
 *
 * @author Snake_Eye
 */
public class dashboard extends javax.swing.JInternalFrame {
    DefaultTableModel defaultTableModel = new DefaultTableModel();
        Connection connection = null;
        PreparedStatement prp = null;
         ResultSet rs = null;
    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
        connection = DataBase.database.ConnectDb();
        
             BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
              bi.setNorthPane(null);
             this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

             tdashun.setBackground(new java.awt.Color(0,0,0,1));
            tdashpass.setBackground(new java.awt.Color(0,0,0,1));
        
        
         
              dash.setBackground(new java.awt.Color(0,0,0,1));
              dash.getViewport().setBackground(new java.awt.Color(0,0,0,1));
              tdash.setBackground(new java.awt.Color(0,0,0,1));
     
         
         JTableHeader header = tdash.getTableHeader();
                 header.setEnabled(false);
        header.setBackground(new java.awt.Color(0,0,0,0));
        tdash.getTableHeader().setFont(new Font("Times New Roman", Font.BOLD, 14));
        
    
        Object columns[] = {"User Name"," Password"};
        defaultTableModel.setColumnIdentifiers(columns);
        tdash.setModel(defaultTableModel);
        tdash.setDefaultEditor(Object.class, null);
         loadData();
    }
        public void loadData() {
        connection = DataBase.database.ConnectDb();
        String sql = "SELECT `username`, `password` FROM `login`";
        try {
            prp = connection.prepareStatement(sql);
            rs = prp.executeQuery();
            Object columnData[] = new Object[2];
            while (rs.next()) {          
                columnData[0] = rs.getString("username");
                columnData[1] = rs.getString("password");
                defaultTableModel.addRow(columnData);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cqa = new javax.swing.JLabel();
        tdashun = new javax.swing.JTextField();
        cqn = new javax.swing.JLabel();
        cqdelete = new javax.swing.JButton();
        tdashpass = new javax.swing.JTextField();
        cqupdate = new javax.swing.JButton();
        cqadd = new javax.swing.JButton();
        dash = new javax.swing.JScrollPane();
        tdash = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(960, 560));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cqa.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        cqa.setForeground(new java.awt.Color(0, 0, 0));
        cqa.setText("Password");
        getContentPane().add(cqa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, 30));

        tdashun.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        tdashun.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tdashun.setOpaque(false);
        tdashun.setPreferredSize(new java.awt.Dimension(6, 22));
        tdashun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdashunActionPerformed(evt);
            }
        });
        getContentPane().add(tdashun, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 160, 20));

        cqn.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        cqn.setForeground(new java.awt.Color(0, 0, 0));
        cqn.setText("User Name");
        getContentPane().add(cqn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 120, 30));

        cqdelete.setBackground(new java.awt.Color(176, 106, 179));
        cqdelete.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        cqdelete.setForeground(new java.awt.Color(0, 0, 204));
        cqdelete.setText("Delete");
        cqdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cqdeleteActionPerformed(evt);
            }
        });
        getContentPane().add(cqdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 80, 40));

        tdashpass.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        tdashpass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tdashpass.setOpaque(false);
        tdashpass.setPreferredSize(new java.awt.Dimension(6, 22));
        getContentPane().add(tdashpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 160, 20));

        cqupdate.setBackground(new java.awt.Color(176, 106, 179));
        cqupdate.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        cqupdate.setForeground(new java.awt.Color(0, 0, 204));
        cqupdate.setText("update");
        cqupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cqupdateActionPerformed(evt);
            }
        });
        getContentPane().add(cqupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 90, 40));

        cqadd.setBackground(new java.awt.Color(176, 106, 179));
        cqadd.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        cqadd.setForeground(new java.awt.Color(0, 0, 204));
        cqadd.setText("Add");
        cqadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cqaddActionPerformed(evt);
            }
        });
        getContentPane().add(cqadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 80, 40));

        dash.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        dash.setOpaque(false);

        tdash.setBackground(new java.awt.Color(176, 106, 179));
        tdash.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tdash.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        tdash.setForeground(new java.awt.Color(0, 0, 0));
        tdash.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tdash.setGridColor(new java.awt.Color(0, 0, 0));
        tdash.setOpaque(false);
        tdash.setRowHeight(20);
        tdash.setSelectionBackground(new java.awt.Color(170, 106, 181));
        tdash.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tdash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tdashMouseClicked(evt);
            }
        });
        dash.setViewportView(tdash);

        getContentPane().add(dash, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 610, 530));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sukiva/images/internal.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tdashunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdashunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdashunActionPerformed

    private void cqdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cqdeleteActionPerformed
        // TODO add your handling code here:
         String username = tdashun.getText();
        String sql = "DELETE FROM `login` WHERE `username` ='" + username + "'";
        try {
            prp = connection.prepareStatement(sql);
            prp.execute();
            JOptionPane.showMessageDialog(null, "Admin " + username + " has been deleted");
            defaultTableModel.getDataVector().removeAllElements();
            defaultTableModel.fireTableDataChanged();
            loadData();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Admin username " + username+ " not found");
        }
                    tdashun.setText("");
                    tdashpass.setText("");
    }//GEN-LAST:event_cqdeleteActionPerformed

    private void cqaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cqaddActionPerformed
        // TODO add your handling code here:
         String username = tdashun.getText();
        String password = tdashpass.getText();

       
            String sql = "INSERT INTO `login`(`username`, `password`) VALUES (?,?)";
            if (connection != null) {

                try {
                    prp = connection.prepareStatement(sql);
                    prp.setString(1, username);
                    prp.setString(2, password);
                    prp.execute();
                    defaultTableModel.getDataVector().removeAllElements();
                    defaultTableModel.fireTableDataChanged();
                    loadData();
                    JOptionPane.showMessageDialog(null, "Data Saved");
                     } 
                catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e);
                
                                            }
                }
                 tdashun.setText("");
                 tdashpass.setText("");
    }//GEN-LAST:event_cqaddActionPerformed

    private void tdashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tdashMouseClicked
        // TODO add your handling code here:
         int row = tdash.getSelectedRow();
        
        tdashun.setText(tdash.getValueAt(row, 0).toString());
        tdashpass.setText(tdash.getValueAt(row, 1).toString());
    }//GEN-LAST:event_tdashMouseClicked

    private void cqupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cqupdateActionPerformed
        // TODO add your handling code here:
         String username = tdashun.getText();
        String password = tdashpass.getText();
        
         
        if(username.equals("")||password.equals("")){

            JOptionPane.showMessageDialog(null,"Complete Your Employer Information","Missing Information",2);

        }
        else {
            String sql = "UPDATE `login` set `username` = '" + username + "', `password` = '" + password + "' where `username` = '" + username + "' or `password` = '" + password + "'";
            try {
                prp = connection.prepareStatement(sql);
                prp.execute();
                defaultTableModel.getDataVector().removeAllElements();
                defaultTableModel.fireTableDataChanged();
                loadData();
                   q.removeAll();
                      dashboard ne = new dashboard();
                     q.add(ne).setVisible(true);
                JOptionPane.showMessageDialog(null, "Data Updated");
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }//GEN-LAST:event_cqupdateActionPerformed

                 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cqa;
    private javax.swing.JButton cqadd;
    private javax.swing.JButton cqdelete;
    private javax.swing.JLabel cqn;
    private javax.swing.JButton cqupdate;
    private javax.swing.JScrollPane dash;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable tdash;
    private javax.swing.JTextField tdashpass;
    private javax.swing.JTextField tdashun;
    // End of variables declaration//GEN-END:variables
}
