/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sukiva;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Snake_Eye
 */
public class stock extends javax.swing.JInternalFrame {

    /**
     * Creates new form shawn
     */
    public stock() {
        initComponents();
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        tdrn.setBackground(new java.awt.Color(0,0,0,1));
        tdri.setBackground(new java.awt.Color(0,0,0,1));
        texd.setBackground(new java.awt.Color(0,0,0,1));
        tqua.setBackground(new java.awt.Color(0,0,0,1));
        tunp.setBackground(new java.awt.Color(0,0,0,1));
        tdis.setBackground(new java.awt.Color(0,0,0,1));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dri = new javax.swing.JLabel();
        exd = new javax.swing.JLabel();
        dis = new javax.swing.JLabel();
        unp = new javax.swing.JLabel();
        drn = new javax.swing.JLabel();
        qua = new javax.swing.JLabel();
        tdri = new javax.swing.JTextField();
        texd = new javax.swing.JTextField();
        tqua = new javax.swing.JTextField();
        tdis = new javax.swing.JTextField();
        tunp = new javax.swing.JTextField();
        tdrn = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(960, 560));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dri.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        dri.setForeground(new java.awt.Color(0, 0, 0));
        dri.setText("Drug ID");
        getContentPane().add(dri, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 120, 30));

        exd.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        exd.setForeground(new java.awt.Color(0, 0, 0));
        exd.setText("EXP Date");
        getContentPane().add(exd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 120, 30));

        dis.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        dis.setForeground(new java.awt.Color(0, 0, 0));
        dis.setText("Distributor");
        getContentPane().add(dis, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 120, 30));

        unp.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        unp.setForeground(new java.awt.Color(0, 0, 0));
        unp.setText("Unit price");
        getContentPane().add(unp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 120, 30));

        drn.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        drn.setForeground(new java.awt.Color(0, 0, 0));
        drn.setText("Drug name");
        getContentPane().add(drn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, 30));

        qua.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        qua.setForeground(new java.awt.Color(0, 0, 0));
        qua.setText("Quantity");
        getContentPane().add(qua, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 120, 30));

        tdri.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        tdri.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tdri.setOpaque(false);
        tdri.setPreferredSize(new java.awt.Dimension(6, 22));
        getContentPane().add(tdri, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 160, 20));

        texd.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        texd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        texd.setOpaque(false);
        texd.setPreferredSize(new java.awt.Dimension(6, 22));
        getContentPane().add(texd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 160, 20));

        tqua.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        tqua.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tqua.setOpaque(false);
        tqua.setPreferredSize(new java.awt.Dimension(6, 22));
        getContentPane().add(tqua, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 160, 20));

        tdis.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        tdis.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tdis.setOpaque(false);
        tdis.setPreferredSize(new java.awt.Dimension(6, 22));
        tdis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdisActionPerformed(evt);
            }
        });
        getContentPane().add(tdis, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 160, 20));

        tunp.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        tunp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tunp.setOpaque(false);
        tunp.setPreferredSize(new java.awt.Dimension(6, 22));
        getContentPane().add(tunp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 160, 20));

        tdrn.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        tdrn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tdrn.setOpaque(false);
        tdrn.setPreferredSize(new java.awt.Dimension(6, 22));
        tdrn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdrnActionPerformed(evt);
            }
        });
        getContentPane().add(tdrn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 160, 20));

        jButton1.setBackground(new java.awt.Color(176, 106, 179));
        jButton1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 204));
        jButton1.setText("Add");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 80, -1));

        jButton2.setBackground(new java.awt.Color(176, 106, 179));
        jButton2.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 204));
        jButton2.setText("Delete");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 80, -1));

        jButton3.setBackground(new java.awt.Color(176, 106, 179));
        jButton3.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 204));
        jButton3.setText("update");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 80, -1));

        bg.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        bg.setForeground(new java.awt.Color(0, 0, 204));
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sukiva/images/large.png"))); // NOI18N
        bg.setText("jLabel1");
        bg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tdisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdisActionPerformed

    private void tdrnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdrnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdrnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel dis;
    private javax.swing.JLabel dri;
    private javax.swing.JLabel drn;
    private javax.swing.JLabel exd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel qua;
    private javax.swing.JTextField tdis;
    private javax.swing.JTextField tdri;
    private javax.swing.JTextField tdrn;
    private javax.swing.JTextField texd;
    private javax.swing.JTextField tqua;
    private javax.swing.JTextField tunp;
    private javax.swing.JLabel unp;
    // End of variables declaration//GEN-END:variables
}
